deployment:
  tasks:
    - export DEPLOYPATH=/home/danp62508434/public_html
    - /opt/cpanel/ea-nodejs18/bin/npm install
    - /opt/cpanel/ea-nodejs18/bin/npm run build
    - /bin/rsync -av --delete build/ $DEPLOYPATH/
